apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-pipelines
  description: Workshop on Jenkins CI/CD pipelines
  tags:
    - devops
    - jenkins
  links:
    - url: https://github.com/deors/workshop-pipelines
      title: Workshop Pipelines
      icon: github
  annotations:
    backstage.io/techdocs-ref: dir:.  
spec:
  lifecycle: production
  type: archetype
  owner: Jorge Hidalgo
  system: public-websites
